apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lvm-init-for-k8s.fullname" . }}
  labels:
    {{- include "lvm-init-for-k8s.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch","patch"]
---
