block-list-secret-scan: []
branch: main
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_K8S_8 # Liveness not applicable for this chart
  - CKV_K8S_9 # Readiness Not applicable for this chart
  - CKV_K8S_15 # "Image Pull Policy should be Always" is not appropriate for public charts
  - CKV_K8S_21 #Default namespace will be changed by admin
  - CKV_K8S_43 #checkov:skip=CKV_K8S_43: Not for Public Charts
  - CKV_K8S_31
  - CKV_K8S_28
  - CKV_K8S_20

summary-position: top
