fullnameOverride: lvm-init-for-k8s
config:
  platform: azure
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: storageClass
              operator: In
              values:
                - nvme
            - key: storageVolumeGroup
              operator: DoesNotExist
tolerations:
  - key: "storageClass"
    operator: "Exists"
  - key: "nvmeReady"
    operator: Equal
    value: "false"
  - key: "computeClass"
    operator: "Exists"
